# Generated by Django 4.2.7 on 2023-11-08 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Documento', models.CharField(max_length=12)),
                ('Nombres', models.CharField(max_length=50)),
                ('ApellidoPaterno', models.CharField(max_length=50)),
                ('ApellidoMaterno', models.CharField(blank=True, max_length=50)),
                ('FechaNacimiento', models.DateField()),
                ('Negocio', models.CharField(max_length=50)),
                ('Cartera', models.CharField(max_length=50)),
                ('Anexo', models.CharField(max_length=4)),
                ('Telefono', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=200)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capacitador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=50)),
                ('ApellidoPaterno', models.CharField(max_length=50)),
                ('ApellidoMaterno', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=20)),
                ('Correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentoCliente', models.CharField(max_length=12)),
                ('CodigoCentral', models.CharField(max_length=10)),
                ('CodArchivo', models.CharField(max_length=60)),
                ('ContactoDirecto', models.BooleanField()),
                ('DetalleLlamada', models.CharField(max_length=500)),
                ('Etapa', models.CharField(max_length=20)),
                ('FechaEvaluacion', models.DateTimeField()),
                ('FechaLlamada', models.DateTimeField()),
                ('Feedback', models.BooleanField()),
                ('FeedbackPendiente', models.BooleanField()),
                ('Nota', models.FloatField()),
                ('Observacion', models.CharField(max_length=500)),
                ('TelefonoCliente', models.CharField(max_length=20)),
                ('TipoGestion', models.CharField(max_length=100)),
                ('AdvertenciaNoPago', models.CharField(max_length=10)),
                ('AsumePDP', models.CharField(max_length=10)),
                ('CaractInform', models.CharField(max_length=10)),
                ('CierreCanalPago', models.CharField(max_length=10)),
                ('ConsOfiAsist', models.CharField(max_length=10)),
                ('ConsultaPago', models.CharField(max_length=10)),
                ('DerivEncuesta', models.CharField(max_length=10)),
                ('Despedida', models.CharField(max_length=10)),
                ('Escuactiva', models.CharField(max_length=10)),
                ('indagaClie', models.CharField(max_length=10)),
                ('IndiGrab', models.CharField(max_length=10)),
                ('MencionNegocio', models.CharField(max_length=10)),
                ('MencionProducto', models.CharField(max_length=10)),
                ('ModulaVoz', models.CharField(max_length=10)),
                ('NoAsumePDP', models.CharField(max_length=10)),
                ('Presenta', models.CharField(max_length=10)),
                ('Saludo', models.CharField(max_length=10)),
                ('TipiFinLlamada', models.CharField(max_length=10)),
                ('Asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad.asesor')),
                ('Capacitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad.capacitador')),
            ],
        ),
        migrations.AddField(
            model_name='capacitador',
            name='Cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad.cargo'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='Capacitador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad.capacitador'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='Estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad.estado'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='Horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad.horario'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='Jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad.jornada'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='Sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad.sexo'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='TipoTrabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad.tipotrabajo'),
        ),
        migrations.AddField(
            model_name='asesor',
            name='Zonal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad.zonal'),
        ),
    ]
